#%RAML 1.0 NamedExample

value:
    id: "2"
    firstName: "Kurt"
    lastName: "Kobain"
    address: "Seatle"
    postal: "5000"
    country: "US"
    creationDate: "2019-07-07T12:48:19+00:00"
    accountType: "BUSINESS"
    miles: 2000